//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package cz.csob.thub.ws.clients.clientlist;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ClientIdentification", targetNamespace = "http://www.csob.cz/distribution/ClientIdentification", wsdlLocation = "WEB-INF/wsdl/GetClientListV2/ClientIdentificationJIGA_1.wsdl")
public class ClientIdentification
    extends Service
{

    private final static URL CLIENTIDENTIFICATION_WSDL_LOCATION;
    private final static WebServiceException CLIENTIDENTIFICATION_EXCEPTION;
    private final static QName CLIENTIDENTIFICATION_QNAME = new QName("http://www.csob.cz/distribution/ClientIdentification", "ClientIdentification");

    static {
            CLIENTIDENTIFICATION_WSDL_LOCATION = cz.csob.thub.ws.clients.clientlist.ClientIdentification.class.getResource("/WEB-INF/wsdl/GetClientListV2/ClientIdentificationJIGA_1.wsdl");
        WebServiceException e = null;
        if (CLIENTIDENTIFICATION_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/GetClientListV2/ClientIdentificationJIGA_1.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CLIENTIDENTIFICATION_EXCEPTION = e;
    }

    public ClientIdentification() {
        super(__getWsdlLocation(), CLIENTIDENTIFICATION_QNAME);
    }

    public ClientIdentification(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTIDENTIFICATION_QNAME, features);
    }

    public ClientIdentification(URL wsdlLocation) {
        super(wsdlLocation, CLIENTIDENTIFICATION_QNAME);
    }

    public ClientIdentification(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTIDENTIFICATION_QNAME, features);
    }

    public ClientIdentification(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientIdentification(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetClientListV2PortType
     */
    @WebEndpoint(name = "GetClientList_v2PortTypeBindingHttpPort")
    public GetClientListV2PortType getGetClientListV2PortTypeBindingHttpPort() {
        return super.getPort(new QName("http://www.csob.cz/distribution/ClientIdentification", "GetClientList_v2PortTypeBindingHttpPort"), GetClientListV2PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetClientListV2PortType
     */
    @WebEndpoint(name = "GetClientList_v2PortTypeBindingHttpPort")
    public GetClientListV2PortType getGetClientListV2PortTypeBindingHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.csob.cz/distribution/ClientIdentification", "GetClientList_v2PortTypeBindingHttpPort"), GetClientListV2PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTIDENTIFICATION_EXCEPTION!= null) {
            throw CLIENTIDENTIFICATION_EXCEPTION;
        }
        return CLIENTIDENTIFICATION_WSDL_LOCATION;
    }

}
