//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package cz.csob.thub.ws.clients.clientlist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "GetClientList_v2PortType", targetNamespace = "http://www.csob.cz/distribution/ClientIdentification")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetClientListV2PortType {


    /**
     * 
     * @param getClientListReqV2
     * @return
     *     returns cz.csob.thub.ws.clients.clientlist.GetClientListRes
     * @throws GeneralFaultV1
     */
    @WebMethod(operationName = "GetClientList_v2", action = "http://www.csob.cz/distribution/ClientIdentification/getClientList/v2")
    @WebResult(name = "GetClientListRes", targetNamespace = "http://www.csob.cz/distribution/ClientIdentification/getClientList/v2", partName = "GetClientListRes_v2")
    public GetClientListRes getClientListV2(
        @WebParam(name = "GetClientListReq", targetNamespace = "http://www.csob.cz/distribution/ClientIdentification/getClientList/v2", partName = "GetClientListReq_v2")
        GetClientListReq getClientListReqV2,
        @WebParam(name = "MetaHeader", targetNamespace = "http://www.csob.cz/common/v1", header = true, partName = "ServiceHeader") MetaHeader metaHeader)
        throws GeneralFaultV1;

}
