//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package cz.csob.thub.ws.clients.disprights;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "DispositionalRights", targetNamespace = "http://www.csob.cz/distribution/DispositionalRights", wsdlLocation = "WEB-INF/wsdl/DispositionalRights/DispositionalRights.GetDrListByProduct_1.wsdl")
public class DispositionalRights
    extends Service
{

    private final static URL DISPOSITIONALRIGHTS_WSDL_LOCATION;
    private final static WebServiceException DISPOSITIONALRIGHTS_EXCEPTION;
    private final static QName DISPOSITIONALRIGHTS_QNAME = new QName("http://www.csob.cz/distribution/DispositionalRights", "DispositionalRights");

    static {
            DISPOSITIONALRIGHTS_WSDL_LOCATION = cz.csob.thub.ws.clients.disprights.DispositionalRights.class.getResource("/WEB-INF/wsdl/DispositionalRights/DispositionalRights.GetDrListByProduct_1.wsdl");
        WebServiceException e = null;
        if (DISPOSITIONALRIGHTS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/DispositionalRights/DispositionalRights.GetDrListByProduct_1.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        DISPOSITIONALRIGHTS_EXCEPTION = e;
    }

    public DispositionalRights() {
        super(__getWsdlLocation(), DISPOSITIONALRIGHTS_QNAME);
    }

    public DispositionalRights(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISPOSITIONALRIGHTS_QNAME, features);
    }

    public DispositionalRights(URL wsdlLocation) {
        super(wsdlLocation, DISPOSITIONALRIGHTS_QNAME);
    }

    public DispositionalRights(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISPOSITIONALRIGHTS_QNAME, features);
    }

    public DispositionalRights(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DispositionalRights(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetDrListByProductV1PortType
     */
    @WebEndpoint(name = "GetDrListByProduct_v1PortTypeBindingHttpPort")
    public GetDrListByProductV1PortType getGetDrListByProductV1PortTypeBindingHttpPort() {
        return super.getPort(new QName("http://www.csob.cz/distribution/DispositionalRights", "GetDrListByProduct_v1PortTypeBindingHttpPort"), GetDrListByProductV1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDrListByProductV1PortType
     */
    @WebEndpoint(name = "GetDrListByProduct_v1PortTypeBindingHttpPort")
    public GetDrListByProductV1PortType getGetDrListByProductV1PortTypeBindingHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.csob.cz/distribution/DispositionalRights", "GetDrListByProduct_v1PortTypeBindingHttpPort"), GetDrListByProductV1PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISPOSITIONALRIGHTS_EXCEPTION!= null) {
            throw DISPOSITIONALRIGHTS_EXCEPTION;
        }
        return DISPOSITIONALRIGHTS_WSDL_LOCATION;
    }

}
