//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package cz.csob.thub.ws.clients.disprights;

import javax.xml.ws.WebFault;

@WebFault(name = "GeneralFault", targetNamespace = "http://services.csob.cz/base_v1")
public class GeneralFaultV1
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GeneralFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GeneralFaultV1(String message, GeneralFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public GeneralFaultV1(String message, GeneralFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cz.csob.thub.ws.clients.disprights.GeneralFault
     */
    public GeneralFault getFaultInfo() {
        return faultInfo;
    }

}
