//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package cz.csob.thub.ws.clients.disprights;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "GetDrListByProduct_v1PortType", targetNamespace = "http://www.csob.cz/distribution/DispositionalRights")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetDrListByProductV1PortType {


    /**
     * 
     * @param getDrListByProductReqV1
     * @return
     *     returns cz.csob.thub.ws.clients.disprights.GetDrListByProductRes
     * @throws GeneralFaultV1
     */
	@WebMethod(operationName = "GetDrListByProduct_v1", action = "http://www.csob.cz/distribution/DispositionalRights/getDrListByProduct/v1")
    @WebResult(name = "GetDrListByProductRes", targetNamespace = "http://www.csob.cz/distribution/DispositionalRights/getDrListByProduct/v1", partName = "GetDrListByProductRes_v1")
	public GetDrListByProductRes getDrListByProductV1(
        @WebParam(name = "GetDrListByProductReq", targetNamespace = "http://www.csob.cz/distribution/DispositionalRights/getDrListByProduct/v1", partName = "GetDrListByProductReq_v1") GetDrListByProductReq getDrListByProductReqV1,
        @WebParam(name = "MetaHeader", targetNamespace = "http://www.csob.cz/common/v1", header = true, partName = "ServiceHeader") MetaHeader metaHeader)
        throws GeneralFaultV1;


}
