//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package cz.csob.thub.ws.clients.disprights;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PagingResType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PagingResType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.csob.cz/common/core}CurrentCount"/>
 *         &lt;element ref="{http://www.csob.cz/common/core}ResultSetCount"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PagingResType", namespace = "http://www.csob.cz/common/v1", propOrder = {
    "currentCount",
    "resultSetCount"
})
public class PagingResType
    implements Serializable
{

    @XmlElement(name = "CurrentCount", namespace = "http://www.csob.cz/common/core", required = true, defaultValue = "1")
    protected BigInteger currentCount;
    @XmlElement(name = "ResultSetCount", namespace = "http://www.csob.cz/common/core", required = true, defaultValue = "1")
    protected BigInteger resultSetCount;

    /**
     * Gets the value of the currentCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCurrentCount() {
        return currentCount;
    }

    /**
     * Sets the value of the currentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCurrentCount(BigInteger value) {
        this.currentCount = value;
    }

    /**
     * Gets the value of the resultSetCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResultSetCount() {
        return resultSetCount;
    }

    /**
     * Sets the value of the resultSetCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResultSetCount(BigInteger value) {
        this.resultSetCount = value;
    }

}
