//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package cz.csob.thub.ws.clients.disprights;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PagingOptType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PagingOptType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://www.csob.cz/common/core}PageNumber"/>
 *           &lt;element ref="{http://www.csob.cz/common/core}RowsPerPage"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://www.csob.cz/common/core}ResultSetMax" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PagingOptType", namespace = "http://www.csob.cz/common/v1", propOrder = {
    "pageNumber",
    "rowsPerPage",
    "resultSetMax"
})
public class PagingOptType
    implements Serializable
{

    @XmlElement(name = "PageNumber", namespace = "http://www.csob.cz/common/core")
    protected BigInteger pageNumber;
    @XmlElement(name = "RowsPerPage", namespace = "http://www.csob.cz/common/core")
    protected BigInteger rowsPerPage;
    @XmlElement(name = "ResultSetMax", namespace = "http://www.csob.cz/common/core", defaultValue = "1")
    protected BigInteger resultSetMax;

    /**
     * Gets the value of the pageNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPageNumber() {
        return pageNumber;
    }

    /**
     * Sets the value of the pageNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPageNumber(BigInteger value) {
        this.pageNumber = value;
    }

    /**
     * Gets the value of the rowsPerPage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRowsPerPage() {
        return rowsPerPage;
    }

    /**
     * Sets the value of the rowsPerPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRowsPerPage(BigInteger value) {
        this.rowsPerPage = value;
    }

    /**
     * Gets the value of the resultSetMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResultSetMax() {
        return resultSetMax;
    }

    /**
     * Sets the value of the resultSetMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResultSetMax(BigInteger value) {
        this.resultSetMax = value;
    }

}
