//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package cz.csob.thub.ws.clients.disprights;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Stadium complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Stadium">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StadiumCode" type="{http://ed6.kbc.com/metaheader.1}StadiumCode"/>
 *         &lt;element name="StadiumDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="256"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Stadium", propOrder = {
    "stadiumCode",
    "stadiumDescription"
})
public class Stadium
    implements Serializable
{

    @XmlElement(name = "StadiumCode", required = true)
    protected StadiumCode stadiumCode;
    @XmlElement(name = "StadiumDescription")
    protected String stadiumDescription;

    /**
     * Gets the value of the stadiumCode property.
     * 
     * @return
     *     possible object is
     *     {@link StadiumCode }
     *     
     */
    public StadiumCode getStadiumCode() {
        return stadiumCode;
    }

    /**
     * Sets the value of the stadiumCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StadiumCode }
     *     
     */
    public void setStadiumCode(StadiumCode value) {
        this.stadiumCode = value;
    }

    /**
     * Gets the value of the stadiumDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStadiumDescription() {
        return stadiumDescription;
    }

    /**
     * Sets the value of the stadiumDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStadiumDescription(String value) {
        this.stadiumDescription = value;
    }

}
